### ISSUE TITLE
Definir horario dos rituais

### ISSUE THREAD

**Issue by BRZangado** [fga-eps-mds/2018.2-GameColorBI#18]
- [x] Criar grade conjunta

**Comment by BRZangado** [comment]
#15

**Comment by nukdown** [comment]
- [ ] Definir horário das daily
- [ ] Definir horário da Sprint Review
- [ ] Definir horário do Sprint Planing

**Comment by nukdown** [comment]
_Decisão tomada_
**Daily Meeting:** 
Horário: 13:45
Freqüência: Segunda a Sexta 
TimeBox 15 min 


**Sprint Review + Sprint Planing:**
14:00 hrs 
Freqüência: Sabado
TImeBox 4 hrs
