### ISSUE TITLE
Planejar e executar treinamento sobre metodologias ágeis

### ISSUE THREAD

**Issue by felipe72** [fga-eps-mds/2018.2-GameColorBI#2]

**Comment by nukdown** [comment]
[x] Manifesto Ágil
[x] Tradicional x Ágil
[x] XP, Scrum
[x] Valores, princípios

**Comment by nukdown** [comment]
- [x] Manifesto Ágil
- [x] Tradicional x Ágil
- [x] XP, Scrum
- [x] Valores, princípios

**Comment by nukdown** [comment]
- [x] Definir dia e horário dos Rituais
