### ISSUE TITLE
Definir local dos Rituais e documentar na wiki

### ISSUE THREAD

**Issue by nukdown** [fga-eps-mds/2018.2-GameColorBI#26]
- [x] Local
- [x] Documentacao

**Comment by nukdown** [comment]
**Daily Meeting:** 
Local: Graminha

**Sprint Review + Sprint Planing** 
Local: Republica 9 Caudas

**Comment by augustovilarins** [comment]
Adicionei as informações na wiki. Elas podem ser vistas no documento "Plano de comunicação"
