### ISSUE TITLE
Planejar reunião inicial com o cliente

### ISSUE THREAD

**Issue by augustovilarins** [fga-eps-mds/2018.2-GameColorBI#27]

**Comment by felipe72** [comment]
Eu acho que a gente precisa discutir com o cliente os seguintes tópicos:

- Escopo da aplicação
- O que já está pronto, pois de acordo com a Carla já tem alguma coisa levantada
- Possíveis tecnologias que podemos utilizar, já que ele é um cliente técnico

 Mais alguma coisa? @augustovilarins @nukdown @BRZangado
